# Course configuration — shared by LaTeX, web, and other tools.

author: Jane Doe
author-short: Doe
institute: Western University
# logo: western-logo.pdf

subject: Calculus
subj: Calc
number: 2402A
# subtitle: Multivariable

term:
  name: Fall 2026
  start: 2026-09-09
  end: 2026-12-09
  readingweek: 2026-10-12
  # noclass:
  #   - 2026-11-11
  # special:
  #   - 2026-10-05: Mock test
  # assessment:
  #   - 2026-09-20: Quiz 1 due
  #   - 2026-09-27: Quiz 2 due
  #   - 2026-09-22: '\faStar{} Test 1'
  #   - 2026-12-10: '\faStar{} Final exam'

sections:
  "001":
    calendar: true
    days:
      - Mon
      - Wed
      - Fri
    time: 1:30 pm to 2:20 pm
  # "002":
  #   days:
  #     - Tue
  #     - Thu
  #   time: 10:30 am to 11:50 am
